server:
  port: 8091

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/application-config
  security:
    user:
      name: configUser
      password: configPassword
      roles: ["SYSTEM"]

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discUser:discPassword@localhost:8092/eureka/